services:
  pg-app:
    image: postgres
    container_name: pg-app
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./app-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  pg-auth:
    image: postgres
    container_name: pg-auth
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./auth-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
