services:
  pg-users:
    image: postgres
    container_name: pg-users
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./user-data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
